# ---------------------------------------------------------------------------
# Regenerate publications/publications.yml from publications/references.bib.
#
# Optional. publications.yml can be maintained by hand; this script exists for
# the case where references.bib is already kept current (e.g. exported from
# Zotero or ORCID) and you would rather not type entries twice.
#
# Usage:
#   Rscript scripts/generate-publications.R
#   Rscript scripts/generate-publications.R --dry-run
#
# Dependencies: RefManageR, yaml. Neither is needed to build the site, so they
# are not part of the deployment workflow.
#
# WARNING: this OVERWRITES publications.yml, including any hand-written
# `description` fields, which BibTeX has no place to store. Run --dry-run first
# and diff the result. A timestamped backup is written next to the target.
# ---------------------------------------------------------------------------

# -- Arguments and paths ----------------------------------------------------

args <- commandArgs(trailingOnly = TRUE)
dry_run <- "--dry-run" %in% args

# Resolve the project root from --file= when run with Rscript, falling back to
# the working directory. sys.frame()$ofile is NULL under Rscript, so it is not
# used here.
script_arg <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
root <- if (length(script_arg)) {
  normalizePath(file.path(dirname(sub("^--file=", "", script_arg[1])), ".."),
                mustWork = FALSE)
} else {
  getwd()
}
if (!dir.exists(file.path(root, "publications"))) root <- getwd()

bib_path <- file.path(root, "publications", "references.bib")
yml_path <- file.path(root, "publications", "publications.yml")

stopifnot(file.exists(bib_path))

for (pkg in c("RefManageR", "yaml")) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    stop("Package '", pkg, "' is required. install.packages('", pkg, "')",
         call. = FALSE)
  }
}

# -- Helpers ----------------------------------------------------------------

# Collapse a BibTeX author list to the display string the site uses. Anything
# more elaborate than "first author et al." is easier to write by hand, so the
# rule is deliberately simple and the output is meant to be reviewed.
format_authors <- function(entry) {
  authors <- entry$author
  if (is.null(authors) || length(authors) == 0L) return("")

  surnames <- vapply(
    authors,
    function(a) paste(unlist(a$family), collapse = " "),
    character(1)
  )
  initials <- vapply(
    authors,
    function(a) paste0(substr(unlist(a$given), 1L, 1L), ".", collapse = ""),
    character(1)
  )

  first <- paste(surnames[1], initials[1])
  if (length(surnames) == 1L) return(first)
  if (length(surnames) == 2L) return(paste0(first, ", ", surnames[2], " ", initials[2]))
  paste0(first, ", et al.")
}

# BibTeX has no month/day for most journal entries, so anything missing becomes
# 1 January. Only the year is displayed; the full date exists to make sorting
# deterministic.
format_date <- function(entry) {
  year <- as.character(entry$year)
  if (length(year) == 0L || is.na(year)) year <- "1900"
  sprintf("%s-01-01", year)
}

split_keywords <- function(entry) {
  kw <- entry$keywords
  if (is.null(kw) || length(kw) == 0L) return(list("Journal article"))
  as.list(trimws(strsplit(as.character(kw), ",")[[1]]))
}

# -- Read and convert -------------------------------------------------------

bib <- RefManageR::ReadBib(bib_path, check = FALSE)

records <- lapply(seq_along(bib), function(i) {
  entry <- bib[[i]]
  doi <- if (length(entry$doi)) as.character(entry$doi) else NULL

  record <- list(
    title = gsub("\\s+", " ", as.character(entry$title)),
    author = format_authors(entry),
    date = format_date(entry),
    journal = if (length(entry$journal)) as.character(entry$journal) else NULL,
    categories = split_keywords(entry)
  )

  if (!is.null(doi)) {
    record$doi <- doi
    record$path <- paste0("https://doi.org/", doi)
  }

  Filter(Negate(is.null), record)
})

# Newest first, matching the listing's default sort.
dates <- vapply(records, function(r) r$date, character(1))
records <- records[order(dates, decreasing = TRUE)]

out <- yaml::as.yaml(records, indent = 2, line.sep = "\n")

header <- paste(
  "# Generated by scripts/generate-publications.R --- do not edit by hand,",
  "# or delete this header once you start editing by hand.",
  paste0("# Source: publications/references.bib. Generated ", Sys.Date(), "."),
  "# NOTE: `description` fields are NOT round-tripped; BibTeX cannot store them.",
  "",
  sep = "\n"
)

# -- Write ------------------------------------------------------------------

if (dry_run) {
  cat(header, out, sep = "")
  message("\n--dry-run: nothing written. ", length(records), " entries.")
} else {
  if (file.exists(yml_path)) {
    backup <- paste0(yml_path, ".", format(Sys.time(), "%Y%m%d%H%M%S"), ".bak")
    file.copy(yml_path, backup, overwrite = FALSE)
    message("Backed up existing file to ", basename(backup))
  }
  writeLines(paste0(header, out), yml_path)
  message("Wrote ", length(records), " entries to ", yml_path)
}
